production:
  host: dinesafe.to
  google_maps_browser_api_key: 
  app_store_link: http://example.org
  app_store_id: 123
  newrelic_license_key: 

development:
  host: dinesafe.dev
  google_maps_browser_api_key: 
  app_store_link: http://example.org
  app_store_id: 123
  newrelic_license_key: 

test: 
  host: 
  google_maps_browser_api_key: 
  app_store_link: http://example.org
  app_store_id: 123
  newrelic_license_key: 
